artifact_uri: file:///Users/ishwarpawar/Desktop/stock_AI/stock-ai/mlflow_runs/333168754795787356/1ae6cca538d943afb71cf2c6d974fed4/artifacts
end_time: 1722670934674
entry_point_name: ''
experiment_id: '333168754795787356'
lifecycle_stage: active
run_id: 1ae6cca538d943afb71cf2c6d974fed4
run_name: trusting-bass-911
run_uuid: 1ae6cca538d943afb71cf2c6d974fed4
source_name: ''
source_type: 4
source_version: ''
start_time: 1722670933315
status: 3
tags: []
user_id: ishwarpawar
