artifact_location: file:///Users/ishwarpawar/Desktop/stock_AI/stock-ai/mlflow_runs/0
creation_time: 1722554750410
experiment_id: '0'
last_update_time: 1722554750410
lifecycle_stage: active
name: Default
