artifact_uri: file:///Users/ishwarpawar/Desktop/stock_AI/stock-ai/mlflow_runs/333168754795787356/e2646804eaca418e9f0acf23cedf79aa/artifacts
end_time: 1722670628098
entry_point_name: ''
experiment_id: '333168754795787356'
lifecycle_stage: active
run_id: e2646804eaca418e9f0acf23cedf79aa
run_name: smiling-mouse-22
run_uuid: e2646804eaca418e9f0acf23cedf79aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1722670628065
status: 3
tags: []
user_id: ishwarpawar
