artifact_uri: file:///Users/ishwarpawar/Desktop/stock_AI/stock-ai/mlflow_runs/333168754795787356/ee13aeaac8fe49dc8f0ea288202ae4ee/artifacts
end_time: 1722699609437
entry_point_name: ''
experiment_id: '333168754795787356'
lifecycle_stage: active
run_id: ee13aeaac8fe49dc8f0ea288202ae4ee
run_name: dapper-doe-47
run_uuid: ee13aeaac8fe49dc8f0ea288202ae4ee
source_name: ''
source_type: 4
source_version: ''
start_time: 1722699151963
status: 3
tags: []
user_id: ishwarpawar
